[[redirects]]
  from = "/*"
  to = "/page-not-found.html"
  status = 404

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
 X-XSS-Protection = "1; mode=block"


 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200